language: objective-c
osx_image: xcode8

script:
    - set -o pipefail

    # Run framework tests
    - xcodebuild
        -project "Popsicle.xcodeproj"
        -scheme "Popsicle"
        -sdk "iphonesimulator10.0"
        -destination "OS=10.0,name=iPhone 6s"
        -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES
        test | xcpretty -c

    # Build demo
    - xcodebuild
        -project "Popsicle.xcodeproj"
        -scheme "PopsicleDemo"
        -sdk "iphonesimulator10.0"
        -destination "OS=10.0,name=iPhone 6s"
        -configuration Debug ONLY_ACTIVE_ARCH=NO
        build | xcpretty -c
